name: suicide-detection
channels:
  - defaults
dependencies:
  - pip=21.2.4
  - python=3.7.11
  - pip:
    - charset-normalizer==2.0.7
    - click==8.0.3
    - colorama==0.4.4
    - filelock==3.3.2
    - huggingface-hub==0.1.2
    - idna==3.3
    - importlib-metadata==4.8.2
    - joblib==1.1.0
    - numpy==1.21.4
    - packaging==21.2
    - pandas==1.3.4
    - pyparsing==2.4.7
    - python-dateutil==2.8.2
    - pytz==2021.3
    - pyyaml==6.0
    - regex==2021.11.10
    - requests==2.26.0
    - sacremoses==0.0.46
    - scikit-learn==1.0.1
    - scipy==1.7.2
    - six==1.16.0
    - sklearn==0.0
    - threadpoolctl==3.0.0
    - tokenizers==0.10.3
    - torch==1.10.0
    - tqdm==4.62.3
    - transformers==4.12.3
    - typing-extensions==3.10.0.2
    - urllib3==1.26.7
    - zipp==3.6.0
